`define AXI_IDLE 3'b000
`define DATA_WAIT_FOR_ARREADY 3'b001
`define DATA_WAIT_FOR_READ_DONE 3'b010
`define INST_WAIT_FOR_ARREADY 3'b011
`define INST_WAIT_FOR_READ_DONE 3'b100

`define DATA_WAIT_FOR_AWREADY 3'b001
`define DATA_WAIT_FOR_WREADY 3'b100
`define DATA_WAIT_FOR_BVALID 3'b101
`define INST_WAIT_FOR_AWREADY 3'b011
`define INST_WAIT_FOR_WREADY 3'b100
`define INST_WAIT_FOR_BVALID 3'b101

`define BURST_FIXED 2'b00
`define BURST_INCR  2'b01
`define BURST_WRAP  2'b10

`define TYPE_BYTE
`define TYPE_HALF_WORD
`define TYPE_WORD
`define TYPE_CACHE_LINE